# Render Blueprint — Automacao-de-Ralatorios-ViaAppia
version: "1"
services:
- type: web
  name: artesp-geojson-api
  runtime: docker
  repo: https://github.com/OzeiasEngler/Automacao-de-Ralatorios-ViaAppia
  plan: standard
  envVars:
  - key: ARTESP_JWT_SECRET
    sync: false
  - key: ARTESP_WEB_USERS
    sync: false
  - key: ARTESP_WEB_PBKDF2_ITERATIONS
    sync: false
  - key: ARTESP_PFX_PASSWORD
    sync: false
  - key: ARTESP_PFX_CONTENT
    sync: false
  region: ohio
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
